In [216]:
import pandas as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [217]:
df = pd.read_csv("/Users/vardhangaur/alzheimer's_ml/data.csv")

In [218]:
df

,ID,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,id_1,5160,0.000013,120.804174,86.853334,957,6601,0.361800,0.217459,103.828754,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.7676,144605,P
1,id_2,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.144880,99.383459,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.2850,298640,P
2,id_3,2600,0.000010,229.933997,172.761858,2333,5802,0.387020,0.181342,201.347928,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.7055,79025,P
3,id_4,2130,0.000010,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,...,0.113905,0.019860,4.206746,1.613522,123,67945,1465.843329,230184.7154,181220,P
4,id_5,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.636510,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.0255,72575,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,id_170,2930,0.000010,241.736477,176.115957,1839,6439,0.253347,0.174663,208.926217,...,0.119152,0.020909,4.508709,2.233198,96,44545,1798.923336,247448.3108,80335,H
170,id_171,2140,0.000009,274.728964,234.495802,2053,8487,0.225537,0.174920,254.612383,...,0.174495,0.017640,4.685573,2.806888,84,37560,1725.619941,160664.6464,345835,H
171,id_172,3830,0.000008,151.536989,171.104693,1287,7352,0.165480,0.161058,161.320841,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,H
172,id_173,1760,0.000008,289.518195,196.411138,1674,6946,0.518937,0.202613,242.964666,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,H
173,id_174,2875,0.000008,235.769350,178.208024,1838,6560,0.567311,0.147818,206.988687,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,H

In [219]:
df['ID'] = df['ID'].str.replace('id_', '').astype(int)

In [220]:
df_new = df.rename(columns={'ID':'Patient_Number'})

In [221]:
df_new.head()

,Patient_Number,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,1,5160,0.000013,120.804174,86.853334,957,6601,0.361800,0.217459,103.828754,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.7676,144605,P
1,2,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.144880,99.383459,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.2850,298640,P
2,3,2600,0.000010,229.933997,172.761858,2333,5802,0.387020,0.181342,201.347928,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.7055,79025,P
3,4,2130,0.000010,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,...,0.113905,0.019860,4.206746,1.613522,123,67945,1465.843329,230184.7154,181220,P
4,5,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.636510,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.0255,72575,P

In [222]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_new['class']=le.fit_transform(df_new['class'])

In [223]:
df_new

,Patient_Number,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,1,5160,0.000013,120.804174,86.853334,957,6601,0.361800,0.217459,103.828754,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.7676,144605,1
1,2,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.144880,99.383459,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.2850,298640,1
2,3,2600,0.000010,229.933997,172.761858,2333,5802,0.387020,0.181342,201.347928,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.7055,79025,1
3,4,2130,0.000010,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,...,0.113905,0.019860,4.206746,1.613522,123,67945,1465.843329,230184.7154,181220,1
4,5,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.636510,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.0255,72575,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,170,2930,0.000010,241.736477,176.115957,1839,6439,0.253347,0.174663,208.926217,...,0.119152,0.020909,4.508709,2.233198,96,44545,1798.923336,247448.3108,80335,0
170,171,2140,0.000009,274.728964,234.495802,2053,8487,0.225537,0.174920,254.612383,...,0.174495,0.017640,4.685573,2.806888,84,37560,1725.619941,160664.6464,345835,0
171,172,3830,0.000008,151.536989,171.104693,1287,7352,0.165480,0.161058,161.320841,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,0
172,173,1760,0.000008,289.518195,196.411138,1674,6946,0.518937,0.202613,242.964666,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,0
173,174,2875,0.000008,235.769350,178.208024,1838,6560,0.567311,0.147818,206.988687,...,0.114472,0.017194,3.493815,2.510601,88,51675,1915.573488,128727.1241,83445,0

In [224]:
df_new.corr()

,Patient_Number,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
Patient_Number,1.000000,-0.085787,-0.172887,0.215877,0.197426,0.036035,0.064383,0.126904,0.040074,0.232662,...,0.278315,0.116641,0.325965,0.284546,-0.137288,-0.337333,0.423317,-0.109289,-0.118127,-0.865811
air_time1,-0.085787,1.000000,0.361259,-0.232732,-0.207819,0.225954,0.014668,0.119806,-0.128735,-0.248715,...,-0.068343,-0.117830,-0.109298,-0.088565,0.023792,0.110482,-0.041226,0.091019,0.018695,0.068355
disp_index1,-0.172887,0.361259,1.000000,-0.246372,-0.385838,0.127803,0.605181,-0.136236,-0.283894,-0.333046,...,-0.135669,0.038488,-0.110590,-0.152034,0.039369,0.153675,-0.111902,0.066591,0.097970,0.222050
gmrt_in_air1,0.215877,-0.232732,-0.246372,1.000000,0.587802,0.133476,0.206822,0.342540,0.455927,0.940325,...,0.187074,0.023682,0.206675,0.127726,-0.128569,-0.170229,0.088930,-0.119840,-0.084335,-0.229922
gmrt_on_paper1,0.197426,-0.207819,-0.385838,0.587802,1.000000,0.245255,0.203036,0.294892,0.875478,0.828012,...,0.149880,-0.121669,0.160714,0.111510,-0.052636,-0.076708,0.113275,-0.045748,-0.093643,-0.196220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
paper_time25,-0.337333,0.110482,0.153675,-0.170229,-0.076708,-0.026867,0.015182,-0.096416,-0.045188,-0.150248,...,-0.509041,-0.332458,-0.551218,-0.600186,0.538560,1.000000,-0.363841,0.418078,0.245180,0.341937
pressure_mean25,0.423317,-0.041226,-0.111902,0.088930,0.113275,-0.043523,0.060988,0.027171,0.069150,0.109281,...,0.436551,0.231458,0.430762,0.447979,-0.237773,-0.363841,1.000000,-0.142470,-0.093414,-0.276503
pressure_var25,-0.109289,0.091019,0.066591,-0.119840,-0.045748,0.074755,-0.099829,0.001428,-0.002497,-0.102302,...,-0.473727,0.013114,-0.428663,-0.359515,0.565881,0.418078,-0.142470,1.000000,0.124291,0.040329
total_time25,-0.118127,0.018695,0.097970,-0.084335,-0.093643,0.054187,-0.002383,-0.031624,-0.060157,-0.097839,...,-0.131651,-0.173553,-0.159280,-0.193496,0.126791,0.245180,-0.093414,0.124291,1.000000,0.111602
class,-0.865811,0.068355,0.222050,-0.229922,-0.196220,-0.058278,0.004928,-0.139833,-0.063417,-0.241889,...,-0.306003,-0.165638,-0.398771,-0.270180,0.136057,0.341937,-0.276503,0.040329,0.111602,1.000000

In [225]:
X = df_new.drop(columns='class')
y = df_new[['class']]

In [226]:
X_train,X_test,y_train,y_test= train_test_split(X,y,random_state=42)

In [227]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

In [228]:
param_grid = {
    'n_estimators': [50, 100, 200],      
    'max_depth': [None, 5, 10],          
    'min_samples_split': [2, 5],
    'criterion':['gini','entropy']        
}

In [ ]:
grid_search = GridSearchCV(
    estimator=model,        # The blank model
    param_grid=param_grid,     # The 18 combinations
    cv=5,                      # 5-fold cross-validation
    scoring='accuracy',        # Grade them based on accuracy
    n_jobs=-1                  # Run tests in parallel using all computer cores
)

grid_search.fit(X_train, y_train)
print("Search complete!")

In [230]:
best_model=grid_search.best_estimator_

In [231]:
final_accuracy = best_model.score(X_test, y_test)

In [232]:
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_pred,y_test)
print(accuracy)

0.9545454545454546

In [233]:
best_params =grid_search.best_params_

In [234]:
print(best_params)

{'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 200}

In [235]:
print()